version: 0.2

env:
  parameter-store:
    DOCKER_USERNAME: "/ci/docker/username"
    DOCKER_PASSWORD: "/ci/docker/password"

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo "Install phase started"

  pre_build:
    commands:
      - echo "Logging in to Docker Hub"
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - echo "Starting local MySQL container for testing"
      - docker run --name test-mysql -e MYSQL_ROOT_PASSWORD=test1234 -e MYSQL_DATABASE=mydb -p 3306:3306 -d mysql:8
      - sleep 20  # wait for DB to initialize
      - echo "MySQL is up"

  build:
    commands:
      - echo "Build phase started"
      - mvn clean install
      - echo "Building Docker image"
      - docker build -t $DOCKER_USERNAME/voucher-service:latest .

  post_build:
    commands:
      - echo "Pushing Docker image"
      - docker push $DOCKER_USERNAME/voucher-service:latest
      - echo "Build completed successfully"

artifacts:
  files:
    - target/*.jar
